# Basic Python

## 1. Split this string

In [6]:
s = "Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [10]:
planet = "Earth"
diameter = 12742


In [11]:
print('The diameter of {} is {} kilometers.'.format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [15]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [17]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros: ")
print(array)

An array of 10 zeros: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives: ")
print(array)

An array of 10 fives: 
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [20]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all even integers from 30 too 70")
print(array)

Array of all even integers from 30 too 70
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [26]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [27]:
c=np.concatenate((a, b)
print(c)

SyntaxError: ignored

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [28]:
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [29]:
import datetime
import pandas as pd
start = datetime.datetime.strptime("01-1-2023", "%d-%m-%Y")
date_generated = pd.date_range(start, periods=10)
print(date_generated.strftime("%d-%m-%Y"))

Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [30]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists)
df.columns = ['col1','col2','col3']
print(df, "\n")

   col1 col2  col3
0     1  aaa    22
1     2  bbb    25
2     3  ccc    24 

